Script started on Wed Feb 22 15:54:48 2017

[1;34;40m[[1;33mTs'ai Meng-hsun[0m@pts/5[0m([1;36mIMSLAB[0m)[1;34m][[1;37m~/test[34m][0m > whoami;pwd
tsaimh
/home/tsaimh/test
[1;34;40m[[1;33mTs'ai Meng-hsun[0m@pts/5[0m([1;36mIMSLAB[0m)[1;34m][[1;37m~/test[34m][0m > git config -l
user.name=ncku-pd2
user.email=tsaimh@csie.ncku.edu.tw
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/menghsun/test.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
[1;34;40m[[1;33mTs'ai Meng-hsun[0m@pts/5[0m([1;36mIMSLAB[0m)[1;34m][[1;37m~/test[34m][0m > git clone https://github.com/ncku-pd2/ lab1.git
Cloning into lab1...
warning: You appear to have cloned an empty repository.
[1;34;40m[[1;33mTs'ai Meng-hsun[0m@pts/5[0m([1;36mIMSLAB[0m)[1;34m][[1;37m~/test[34m][0m > ls
lab1		lab1.script	test1.cpp
[1;34;40m[[1;33mTs'ai Meng-hsun[0m@pts/5[0m([1;36mIMSLAB[0m)[1;34m][[1;37m~/test[34m][0m > ^Dexit

Script done on Wed Feb 22 15:55:34 2017
